// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230824190005_OrderentityAdded")]
    partial class OrderentityAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Description = "Apple Inc. is an American multinational technology company headquarted in Cupertino, California.",
                            ImageUrl = "images/brands/logo/apple_black.png",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Description = "Samsung is is a South Korean multinational manufacturing conglomerate headquartered in Samsung Town, Seoul, South Korea.",
                            ImageUrl = "images/brands/logo/samsung_blue.png",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = new Guid("d68fe072-2a4c-4990-acdb-08db70f8ca7e"),
                            Description = "Xiaomi Corporation is a Chinese designer and manufacturer of consumer electronics and related software items.",
                            ImageUrl = "images/brands/logo/xiaomi.png",
                            Name = "Xiaomi"
                        },
                        new
                        {
                            Id = new Guid("a00b5685-3066-4665-acdc-08db70f8ca7e"),
                            Description = "Dell Inc. is an American based technology company. It develops, sells, repairs, and supports computers and related products and services.",
                            ImageUrl = "images/brands/logo/dell.png",
                            Name = "Dell"
                        },
                        new
                        {
                            Id = new Guid("e2c7db35-24ee-4661-3f2a-08db7287ca33"),
                            Description = "Sony is a Japanese multinational conglomerate corporation headquartered in Minato, Tokyo, Japan.",
                            ImageUrl = "images/brands/logo/sony.png",
                            Name = "Sony"
                        },
                        new
                        {
                            Id = new Guid("8203e247-da1b-4922-3f2b-08db7287ca33"),
                            Description = "Motorola is an American multinational telecommunications company based in Schaumburg, Illinois.",
                            ImageUrl = "images/brands/logo/motorola.png",
                            Name = "Motorola"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e6fb337-af84-4046-9a9c-ddc4e4e6e640"),
                            Description = "Category of electronic goods",
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = new Guid("bd84693a-702e-4fb2-ba16-d93ae8e8e204"),
                            Description = "Category of electronic goods",
                            Name = "Tablets"
                        },
                        new
                        {
                            Id = new Guid("94a41fec-e15f-4d46-ac7d-2e648168f051"),
                            Description = "Category of electronic goods",
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = new Guid("323c0bf7-c4b5-4b0c-58db-08db718ecbd1"),
                            Description = "Category of electronic goods",
                            Name = "Smartwatches"
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderAggregate.DeliveryMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(38,2)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0747c069-6463-47fa-8604-229a9e93ed8a"),
                            DeliveryTime = "1-2 Days",
                            Description = "Fastest delivery time",
                            Price = 10m,
                            ShortName = "UPS1"
                        },
                        new
                        {
                            Id = new Guid("12b13ad8-1edf-4075-afd5-bf3b5b413220"),
                            DeliveryTime = "2-5 Days",
                            Description = "Get it within 5 days",
                            Price = 5m,
                            ShortName = "UPS2"
                        },
                        new
                        {
                            Id = new Guid("ee00c5a6-bb2d-454b-ab4a-f28fdc9d1d9f"),
                            DeliveryTime = "5-10 Days",
                            Description = "Slower but cheap",
                            Price = 2m,
                            ShortName = "UPS3"
                        },
                        new
                        {
                            Id = new Guid("bdca0a3a-2087-4861-9e77-6965fe1b0d34"),
                            DeliveryTime = "1-2 Weeks",
                            Description = "Free! You get what you pay for",
                            Price = 0m,
                            ShortName = "FREE"
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeliveryMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentItentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(38,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryMethodId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Entities.OrderAggregate.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(38,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(38,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2a61f54-c74d-4ebf-fd82-08db73e17d2c"),
                            BrandId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CategoryId = new Guid("9e6fb337-af84-4046-9a9c-ddc4e4e6e640"),
                            ImageUrl = "images/brands/products/apple_iphone_14_pro_256gb_deep_purple.jpeg",
                            Name = "Apple iPhone 14 Pro 256Gb Deep Purple",
                            Price = 1120m
                        },
                        new
                        {
                            Id = new Guid("f31707ce-d118-45a0-86fe-bbcfed519301"),
                            BrandId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CategoryId = new Guid("9e6fb337-af84-4046-9a9c-ddc4e4e6e640"),
                            ImageUrl = "images/brands/products/apple_iphone_14_pro_128gb_gold.jpeg",
                            Name = "Apple iPhone 14 Pro 128Gb Gold",
                            Price = 920m
                        },
                        new
                        {
                            Id = new Guid("c0cbd5fe-454b-4be9-a4b0-859d70c8cc82"),
                            BrandId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CategoryId = new Guid("9e6fb337-af84-4046-9a9c-ddc4e4e6e640"),
                            ImageUrl = "images/brands/products/apple_iphone_12_128gb_silver.jpeg",
                            Name = "Apple iPhone 12 128Gb Silver",
                            Price = 420m
                        },
                        new
                        {
                            Id = new Guid("41d749b4-6381-4281-a513-eb5552a22996"),
                            BrandId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CategoryId = new Guid("bd84693a-702e-4fb2-ba16-d93ae8e8e204"),
                            ImageUrl = "images/brands/products/apple_ipad_10.2_64gb_space_grey.jpeg",
                            Name = "Apple iPad 10.2 64Gb Space Grey",
                            Price = 260m
                        },
                        new
                        {
                            Id = new Guid("39348e22-1a62-444c-b62b-575ece82c251"),
                            BrandId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CategoryId = new Guid("bd84693a-702e-4fb2-ba16-d93ae8e8e204"),
                            ImageUrl = "images/brands/products/apple_ipad_11_128gb_silver.jpeg",
                            Name = "Apple iPad 11 128Gb Silver",
                            Price = 930m
                        },
                        new
                        {
                            Id = new Guid("b04d673e-7317-4524-fd7f-08db73e17d2c"),
                            BrandId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CategoryId = new Guid("323c0bf7-c4b5-4b0c-58db-08db718ecbd1"),
                            ImageUrl = "images/brands/products/apple_silver_aluminum_case_with_sport_band.jpeg",
                            Name = "Apple Silver Aluminum Case with Sport Band",
                            Price = 399m
                        },
                        new
                        {
                            Id = new Guid("fdb7556f-f61a-4024-fd80-08db73e17d2c"),
                            BrandId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CategoryId = new Guid("323c0bf7-c4b5-4b0c-58db-08db718ecbd1"),
                            ImageUrl = "images/brands/products/apple_starlight_aluminum_case_with_braided_solo_loop.jpeg",
                            Name = "Apple Starlight Aluminum Case with Braided Solo Loop",
                            Price = 449m
                        },
                        new
                        {
                            Id = new Guid("34712f2c-46d5-4920-fd81-08db73e17d2c"),
                            BrandId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CategoryId = new Guid("323c0bf7-c4b5-4b0c-58db-08db718ecbd1"),
                            ImageUrl = "images/brands/products/apple_midnight_aluminum_case_with_sport_loop.jpeg",
                            Name = "Apple Midnight Aluminum Case with Sport Loop",
                            Price = 1120m
                        },
                        new
                        {
                            Id = new Guid("aba5a6ca-2625-4d9a-9130-8fee866667ee"),
                            BrandId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CategoryId = new Guid("94a41fec-e15f-4d46-ac7d-2e648168f051"),
                            ImageUrl = "images/brands/products/apple_macbook_air_13_mgn63_silver.jpeg",
                            Name = "Apple MacBook Air 13 MGN63 Silver",
                            Price = 970m
                        },
                        new
                        {
                            Id = new Guid("b48f982c-02a5-47b0-922b-b8ac76524a39"),
                            BrandId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CategoryId = new Guid("94a41fec-e15f-4d46-ac7d-2e648168f051"),
                            ImageUrl = "images/brands/products/apple_macbook_air_13_mgnd3_gold.jpeg",
                            Name = "Apple MacBook Air 13 MGND3 Gold",
                            Price = 1000m
                        },
                        new
                        {
                            Id = new Guid("b2c21d7d-410d-4435-b86d-82590ae58937"),
                            BrandId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            CategoryId = new Guid("9e6fb337-af84-4046-9a9c-ddc4e4e6e640"),
                            ImageUrl = "images/brands/products/samsung_galaxy_a23 6gb_128gb_black.jpeg",
                            Name = "Samsung Galaxy A23 6Gb/128Gb Black",
                            Price = 210m
                        },
                        new
                        {
                            Id = new Guid("d25d4d14-bf96-4dee-a5b3-d3bd0a083ade"),
                            BrandId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            CategoryId = new Guid("9e6fb337-af84-4046-9a9c-ddc4e4e6e640"),
                            ImageUrl = "images/brands/products/samsung_galaxy_a13_4gb_64gb_blue.jpeg",
                            Name = "Samsung Galaxy A13 4Gb/64Gb Blue",
                            Price = 160m
                        },
                        new
                        {
                            Id = new Guid("b295bbe2-03c8-437a-de07-08db71b2f7e8"),
                            BrandId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            CategoryId = new Guid("9e6fb337-af84-4046-9a9c-ddc4e4e6e640"),
                            ImageUrl = "images/brands/products/samsung_galaxy_a03_4gb_64gb_blue.jpeg",
                            Name = "Samsung Galaxy A03 4Gb/64Gb Blue",
                            Price = 145m
                        },
                        new
                        {
                            Id = new Guid("def34053-91a6-4086-bfe6-19115867d5bb"),
                            BrandId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            CategoryId = new Guid("bd84693a-702e-4fb2-ba16-d93ae8e8e204"),
                            ImageUrl = "images/brands/products/samsung_galaxy_tab_a7_lite_8.7_sm-t220_gray.jpeg",
                            Name = "Samsung Galaxy Tab A7 Lite 8.7 SM-T220 Gray",
                            Price = 110m
                        },
                        new
                        {
                            Id = new Guid("cfcec647-6934-4627-9fdb-8694ca5302ff"),
                            BrandId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            CategoryId = new Guid("bd84693a-702e-4fb2-ba16-d93ae8e8e204"),
                            ImageUrl = "images/brands/products/samsung_galaxy_tab_a8_10.5_sm-x205n_gray.jpeg",
                            Name = "Samsung Galaxy Tab A8 10.5 SM-X205N Gray",
                            Price = 220m
                        },
                        new
                        {
                            Id = new Guid("6519c192-93c5-48e6-bb34-04ed481f90ca"),
                            BrandId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            CategoryId = new Guid("94a41fec-e15f-4d46-ac7d-2e648168f051"),
                            ImageUrl = "images/brands/products/samsung_galaxy_book3_ultra.jpeg",
                            Name = "Samsung Galaxy Book3 Ultra",
                            Price = 800m
                        },
                        new
                        {
                            Id = new Guid("8d8a7376-49ee-4f6c-89c0-f555c04b4caa"),
                            BrandId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            CategoryId = new Guid("94a41fec-e15f-4d46-ac7d-2e648168f051"),
                            ImageUrl = "images/brands/products/samsung_galaxy_book3_pro_360.jpeg",
                            Name = "Samsung Galaxy Book3 Pro 360",
                            Price = 1100m
                        },
                        new
                        {
                            Id = new Guid("5bcdada4-71ef-45e2-b3c3-08db731e86dd"),
                            BrandId = new Guid("8203e247-da1b-4922-3f2b-08db7287ca33"),
                            CategoryId = new Guid("9e6fb337-af84-4046-9a9c-ddc4e4e6e640"),
                            ImageUrl = "images/brands/products/motorola_razr_64gb.jpeg",
                            Name = "Motorola Razr 64Gb",
                            Price = 230m
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderAggregate.Order", b =>
                {
                    b.HasOne("Domain.Entities.OrderAggregate.DeliveryMethod", "DeliveryMethod")
                        .WithMany()
                        .HasForeignKey("DeliveryMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Entities.OrderAggregate.Address", "ShipToAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("DeliveryMethod");

                    b.Navigation("ShipToAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.OrderAggregate.OrderItem", b =>
                {
                    b.HasOne("Domain.Entities.OrderAggregate.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Domain.Entities.OrderAggregate.ProductItemOrdered", "ItemOrdered", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("ItemOrdered")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.OrderAggregate.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
